#include <Arduino.h>
String web="<!DOCTYPE html>"
"<html>"
"<head>"
"  <title>indexM</title>"
"  <style>"
"    body {"
"      font-family: \"Arial\", sans-serif;"
"      display: flex;"
"      justify-content: center;"
"      align-items: center;"
"      text-align: center;"
"      min-height: 100vh;"
"      margin: 0;"
"      background-color: #f2f2f2;"
"    }"
"    .container {"
"      max-width: 400px;"
"      padding: 40px;"
"      background-color: #fff;"
"      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);"
"      border-radius: 8px;"
"    }"
"    h1 {"
"      color: #333;"
"      font-size: 24px;"
"      margin-bottom: 20px;"
"    }"
"    a {"
"      display: block;"
"      color: #555;"
"      text-decoration: none;"
"      margin-bottom: 16px;"
"    }"
"  </style>"
"</head>"
"<body>"
"  <div class=\"container\">"
"    <h1>Museo del Louvre</h1>"
"    <a href=\"../html/pintura.html\">Pintura</a>"
"    <a href=\"../html/escultura.html\">Escultura</a>"
"  </div>"
"</body>"
"</html>";
